import React, { createContext, useContext, useState } from 'react';
/* eslint-disable no-dupe-keys, react-refresh/only-export-components */

const translations = {
  en: {
    home: 'Home',
    features: 'Features',
    about: 'About',
    contact: 'Contact',
    buildTeams: 'Build great teams',
    login: 'Login',
    getStarted: 'Get Started',
    logout: 'Logout',
    hi: 'Hi',
    admin: 'Admin',
    client: 'Client',
    freelancer: 'Freelancer',

    hireTopTalent: 'Hire Top Talent',
    hireSubtitle: 'Connect with expert freelancers ready for your next project',
    postProject: 'Post Your Project',
    postSubtitle: 'Get proposals from global talent within hours',
    collaborateSeamlessly: 'Collaborate Seamlessly',
    collaborateSubtitle: 'Secure payments, milestones, and real-time communication',
    getStartedFree: 'Get Started Free',
    howItWorks: 'How It Works',
    freelancers: 'Freelancers',
    onlineNow: 'online right now',
    avgRating: 'Avg rating',
    countries: 'Countries',
    securePayments: 'Secure payments',
    simpleSteps: '4 SIMPLE STEPS',
    howWorks: 'How Freelancer Marketplace Works',
    howDesc: 'From idea to finished project — fast, safe, and stress-free.',
    signUpFree: 'Sign Up for Free',
    signUpDesc: 'Create your account in 30 seconds and start immediately.',
    postProjectStep: 'Post Your Project',
    postDesc: 'Describe your needs, budget, and deadline. It\'s 100% free.',
    receiveProposals: 'Receive Proposals',
    receiveDesc: 'Qualified freelancers send you offers with their portfolios.',
    hireSecurely: 'Hire & Pay Securely',
    hireDesc: 'Choose the best match, pay through milestones, and get the job done.',
    popularCategories: 'Popular Categories',
    browseAll: 'Browse all',
    projects: 'projects',
    featuredFreelancers: 'Featured Freelancers This Week',
    whatClientsSay: 'What Our Clients Say',
    readyHire: 'Ready to hire or get hired?',
    joinUs: 'Join thousands of businesses and freelancers already growing with us.',
    createAccount: 'Create Free Account',

    loginToAccount: 'Login to your account',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember Me',
    forgotPassword: 'Forgot Password?',
    loggingIn: 'Logging In…',
    login: 'Login',

    createAccount: 'Create Account',
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    selectRole: 'Select Role:',
    client: 'Client',
    freelancer: 'Freelancer',
    creating: 'Creating…',
    createAccountBtn: 'Create Account',
    alreadyAccount: 'Already have an account?',
  },
  al: {
    home: 'Kryefaqja',
    features: 'Karakteristikat',
    about: 'Rreth Nesh',
    contact: 'Kontakti',
    buildTeams: 'Ndërto ekipe të shkëlqyera',
    login: 'Hyni',
    getStarted: 'Filloni',
    logout: 'Dilni',
    hi: 'Përshëndetje',
    admin: 'Admin',
    client: 'Klient',
    freelancer: 'Freelancer',

    hireTopTalent: 'Punësoni Talente të Larta',
    hireSubtitle: 'Lidhuni me freelancer ekspertë gati për projektin tuaj të ardhshëm',
    postProject: 'Postoni Projektin Tuaj',
    postSubtitle: 'Merrni propozime nga talenti global brenda orëve',
    collaborateSeamlessly: 'Bashkëpunoni Pa Probleme',
    collaborateSubtitle: 'Pagesa të sigurta, milestone dhe komunikim në kohë reale',
    getStartedFree: 'Filloni Falas',
    howItWorks: 'Si Funksionon',
    freelancers: 'Freelancer',
    onlineNow: 'online tani',
    avgRating: 'Vlerësimi mesatar',
    countries: 'Vendet',
    securePayments: 'Pagesa të sigurta',
    simpleSteps: '4 HAP SIMPLES',
    howWorks: 'Si Funksionon Freelancer Marketplace',
    howDesc: 'Nga ideja në projekt të përfunduar — shpejt, sigurt dhe pa stres.',
    signUpFree: 'Regjistrohuni Falas',
    signUpDesc: 'Krijoni llogarinë tuaj në 30 sekonda dhe filloni menjëherë.',
    postProjectStep: 'Postoni Projektin Tuaj',
    postDesc: 'Përshkruani nevojat tuaja, buxhetin dhe afatin. Është 100% falas.',
    receiveProposals: 'Merrni Propozime',
    receiveDesc: 'Freelancer të kualifikuar ju dërgojnë oferta me portofolin e tyre.',
    hireSecurely: 'Punësoni & Paguani Sigurt',
    hireDesc: 'Zgjidhni ndeshjen më të mirë, paguani përmes milestone dhe përfundoni punën.',
    popularCategories: 'Kategoritë Popullore',
    browseAll: 'Shfletoni të gjitha',
    projects: 'projektet',
    featuredFreelancers: 'Freelancer të Zgjedhur Këtë Javë',
    whatClientsSay: 'Çfarë Thonë Klientët Tanë',
    readyHire: 'Gati për të punësuar ose për t\'u punësuar?',
    joinUs: 'Bashkohuni me mijëra biznese dhe freelancer që po rriten me ne.',
    createAccount: 'Krijoni Llogari Falas',

    loginToAccount: 'Hyni në llogarinë tuaj',
    email: 'Email',
    password: 'Fjalëkalimi',
    rememberMe: 'Më kujto',
    forgotPassword: 'Keni harruar fjalëkalimin?',
    loggingIn: 'Duke hyrë…',
    login: 'Hyni',

    createAccount: 'Krijoni Llogari',
    fullName: 'Emri i Plotë',
    confirmPassword: 'Konfirmo Fjalëkalimin',
    selectRole: 'Zgjidhni Rolin:',
    client: 'Klient',
    freelancer: 'Freelancer',
    creating: 'Duke krijuar…',
    createAccountBtn: 'Krijoni Llogari',
    alreadyAccount: 'Keni tashmë një llogari?',
  },
  de: {
    home: 'Startseite',
    features: 'Funktionen',
    about: 'Über uns',
    contact: 'Kontakt',
    buildTeams: 'Großartige Teams aufbauen',
    login: 'Anmelden',
    getStarted: 'Loslegen',
    logout: 'Abmelden',
    hi: 'Hallo',
    admin: 'Admin',
    client: 'Kunde',
    freelancer: 'Freelancer',

    hireTopTalent: 'Top-Talente einstellen',
    hireSubtitle: 'Verbinden Sie sich mit erfahrenen Freelancern für Ihr nächstes Projekt',
    postProject: 'Projekt veröffentlichen',
    postSubtitle: 'Erhalten Sie Angebote von globalen Talenten innerhalb von Stunden',
    collaborateSeamlessly: 'Nahtlos zusammenarbeiten',
    collaborateSubtitle: 'Sichere Zahlungen, Meilensteine und Echtzeitkommunikation',
    getStartedFree: 'Kostenlos starten',
    howItWorks: 'Wie es funktioniert',
    freelancers: 'Freelancer',
    onlineNow: 'jetzt online',
    avgRating: 'Durchschnittliche Bewertung',
    countries: 'Länder',
    securePayments: 'Sichere Zahlungen',
    simpleSteps: '4 EINFACHE SCHRITTE',
    howWorks: 'Wie Freelancer Marketplace funktioniert',
    howDesc: 'Von der Idee zum fertigen Projekt — schnell, sicher und stressfrei.',
    signUpFree: 'Kostenlos anmelden',
    signUpDesc: 'Erstellen Sie Ihr Konto in 30 Sekunden und starten Sie sofort.',
    postProjectStep: 'Ihr Projekt veröffentlichen',
    postDesc: 'Beschreiben Sie Ihre Bedürfnisse, Budget und Frist. Es ist 100% kostenlos.',
    receiveProposals: 'Angebote erhalten',
    receiveDesc: 'Qualifizierte Freelancer senden Ihnen Angebote mit ihren Portfolios.',
    hireSecurely: 'Sicher einstellen & bezahlen',
    hireDesc: 'Wählen Sie die beste Übereinstimmung, zahlen Sie über Meilensteine und lassen Sie die Arbeit erledigen.',
    popularCategories: 'Beliebte Kategorien',
    browseAll: 'Alle durchsuchen',
    projects: 'Projekte',
    featuredFreelancers: 'Ausgewählte Freelancer diese Woche',
    whatClientsSay: 'Was unsere Kunden sagen',
    readyHire: 'Bereit einzustellen oder eingestellt zu werden?',
    joinUs: 'Treten Sie Tausenden von Unternehmen und Freelancern bei, die mit uns wachsen.',
    createAccount: 'Kostenloses Konto erstellen',

    loginToAccount: 'In Ihr Konto einloggen',
    email: 'E-Mail',
    password: 'Passwort',
    rememberMe: 'Eingeloggt bleiben',
    forgotPassword: 'Passwort vergessen?',
    loggingIn: 'Einloggen…',
    login: 'Anmelden',

    createAccount: 'Konto erstellen',
    fullName: 'Vollständiger Name',
    confirmPassword: 'Passwort bestätigen',
    selectRole: 'Rolle auswählen:',
    client: 'Kunde',
    freelancer: 'Freelancer',
    creating: 'Erstellen…',
    createAccountBtn: 'Konto erstellen',
    alreadyAccount: 'Haben Sie bereits ein Konto?',
  },
  it: {
    home: 'Home',
    features: 'Caratteristiche',
    about: 'Chi siamo',
    contact: 'Contatto',
    buildTeams: 'Costruisci grandi team',
    login: 'Accedi',
    getStarted: 'Inizia',
    logout: 'Esci',
    hi: 'Ciao',
    admin: 'Admin',
    client: 'Cliente',
    freelancer: 'Freelancer',

    hireTopTalent: 'Assumi Talenti di Alto Livello',
    hireSubtitle: 'Connettiti con freelancer esperti pronti per il tuo prossimo progetto',
    postProject: 'Pubblica il Tuo Progetto',
    postSubtitle: 'Ricevi proposte da talenti globali entro poche ore',
    collaborateSeamlessly: 'Collabora Senza Problemi',
    collaborateSubtitle: 'Pagamenti sicuri, milestone e comunicazione in tempo reale',
    getStartedFree: 'Inizia Gratuitamente',
    howItWorks: 'Come Funziona',
    freelancers: 'Freelancer',
    onlineNow: 'online ora',
    avgRating: 'Valutazione media',
    countries: 'Paesi',
    securePayments: 'Pagamenti sicuri',
    simpleSteps: '4 SEMPLICI PASSI',
    howWorks: 'Come Funziona Freelancer Marketplace',
    howDesc: 'Dall\'idea al progetto finito — veloce, sicuro e senza stress.',
    signUpFree: 'Iscriviti Gratuitamente',
    signUpDesc: 'Crea il tuo account in 30 secondi e inizia immediatamente.',
    postProjectStep: 'Pubblica il Tuo Progetto',
    postDesc: 'Descrivi le tue esigenze, budget e scadenza. È 100% gratuito.',
    receiveProposals: 'Ricevi Proposte',
    receiveDesc: 'Freelancer qualificati ti inviano offerte con i loro portfolio.',
    hireSecurely: 'Assumi & Paga Sicuramente',
    hireDesc: 'Scegli la migliore corrispondenza, paga attraverso milestone e fai completare il lavoro.',
    popularCategories: 'Categorie Popolari',
    browseAll: 'Sfoglia tutto',
    projects: 'progetti',
    featuredFreelancers: 'Freelancer in Evidenza Questa Settimana',
    whatClientsSay: 'Cosa Dicono i Nostri Clienti',
    readyHire: 'Pronto ad assumere o essere assunto?',
    joinUs: 'Unisciti a migliaia di aziende e freelancer che stanno crescendo con noi.',
    createAccount: 'Crea Account Gratuito',

    loginToAccount: 'Accedi al tuo account',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Ricordami',
    forgotPassword: 'Password dimenticata?',
    loggingIn: 'Accesso in corso…',
    login: 'Accedi',

    createAccount: 'Crea Account',
    fullName: 'Nome Completo',
    confirmPassword: 'Conferma Password',
    selectRole: 'Seleziona Ruolo:',
    client: 'Cliente',
    freelancer: 'Freelancer',
    creating: 'Creazione in corso…',
    createAccountBtn: 'Crea Account',
    alreadyAccount: 'Hai già un account?',
  },
  fr: {
    home: 'Accueil',
    features: 'Fonctionnalités',
    about: 'À propos',
    contact: 'Contact',
    buildTeams: 'Construire de grandes équipes',
    login: 'Se connecter',
    getStarted: 'Commencer',
    logout: 'Se déconnecter',
    hi: 'Salut',
    admin: 'Admin',
    client: 'Client',
    freelancer: 'Freelancer',

    hireTopTalent: 'Embaucher les Meilleurs Talents',
    hireSubtitle: 'Connectez-vous avec des freelancers experts prêts pour votre prochain projet',
    postProject: 'Publier Votre Projet',
    postSubtitle: 'Recevez des propositions de talents mondiaux en quelques heures',
    collaborateSeamlessly: 'Collaborez Sans Effort',
    collaborateSubtitle: 'Paiements sécurisés, jalons et communication en temps réel',
    getStartedFree: 'Commencer Gratuitement',
    howItWorks: 'Comment Ça Marche',
    freelancers: 'Freelancers',
    onlineNow: 'en ligne maintenant',
    avgRating: 'Note moyenne',
    countries: 'Pays',
    securePayments: 'Paiements sécurisés',
    simpleSteps: '4 ÉTAPES SIMPLES',
    howWorks: 'Comment Freelancer Marketplace Fonctionne',
    howDesc: 'De l\'idée au projet fini — rapide, sûr et sans stress.',
    signUpFree: 'S\'inscrire Gratuitement',
    signUpDesc: 'Créez votre compte en 30 secondes et commencez immédiatement.',
    postProjectStep: 'Publier Votre Projet',
    postDesc: 'Décrivez vos besoins, budget et échéance. C\'est 100% gratuit.',
    receiveProposals: 'Recevoir des Propositions',
    receiveDesc: 'Des freelancers qualifiés vous envoient des offres avec leurs portfolios.',
    hireSecurely: 'Embaucher & Payer Sécurément',
    hireDesc: 'Choisissez la meilleure correspondance, payez via jalons et faites terminer le travail.',
    popularCategories: 'Catégories Populaires',
    browseAll: 'Tout parcourir',
    projects: 'projets',
    featuredFreelancers: 'Freelancers en Vedette Cette Semaine',
    whatClientsSay: 'Ce Que Disent Nos Clients',
    readyHire: 'Prêt à embaucher ou être embauché?',
    joinUs: 'Rejoignez des milliers d\'entreprises et de freelancers qui grandissent avec nous.',
    createAccount: 'Créer un Compte Gratuit',

    loginToAccount: 'Connectez-vous à votre compte',
    email: 'Email',
    password: 'Mot de passe',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié?',
    loggingIn: 'Connexion en cours…',
    login: 'Se connecter',

    createAccount: 'Créer un Compte',
    fullName: 'Nom Complet',
    confirmPassword: 'Confirmer le Mot de Passe',
    selectRole: 'Sélectionner le Rôle:',
    client: 'Client',
    freelancer: 'Freelancer',
    creating: 'Création en cours…',
    createAccountBtn: 'Créer un Compte',
    alreadyAccount: 'Vous avez déjà un compte?',
  },
  es: {
    home: 'Inicio',
    features: 'Características',
    about: 'Acerca de',
    contact: 'Contacto',
    buildTeams: 'Construir grandes equipos',
    login: 'Iniciar sesión',
    getStarted: 'Comenzar',
    logout: 'Cerrar sesión',
    hi: 'Hola',
    admin: 'Admin',
    client: 'Cliente',
    freelancer: 'Freelancer',

    hireTopTalent: 'Contratar Talentos de Alto Nivel',
    hireSubtitle: 'Conéctate con freelancers expertos listos para tu próximo proyecto',
    postProject: 'Publicar Tu Proyecto',
    postSubtitle: 'Recibe propuestas de talento global en horas',
    collaborateSeamlessly: 'Colabora Sin Problemas',
    collaborateSubtitle: 'Pagos seguros, hitos y comunicación en tiempo real',
    getStartedFree: 'Comenzar Gratis',
    howItWorks: 'Cómo Funciona',
    freelancers: 'Freelancers',
    onlineNow: 'en línea ahora',
    avgRating: 'Calificación promedio',
    countries: 'Países',
    securePayments: 'Pagos seguros',
    simpleSteps: '4 PASOS SIMPLES',
    howWorks: 'Cómo Funciona Freelancer Marketplace',
    howDesc: 'Desde la idea hasta el proyecto terminado — rápido, seguro y sin estrés.',
    signUpFree: 'Registrarse Gratis',
    signUpDesc: 'Crea tu cuenta en 30 segundos y comienza inmediatamente.',
    postProjectStep: 'Publicar Tu Proyecto',
    postDesc: 'Describe tus necesidades, presupuesto y plazo. Es 100% gratis.',
    receiveProposals: 'Recibir Propuestas',
    receiveDesc: 'Freelancers calificados te envían ofertas con sus portafolios.',
    hireSecurely: 'Contratar & Pagar Seguros',
    hireDesc: 'Elige la mejor coincidencia, paga a través de hitos y haz que se complete el trabajo.',
    popularCategories: 'Categorías Populares',
    browseAll: 'Explorar todo',
    projects: 'proyectos',
    featuredFreelancers: 'Freelancers Destacados Esta Semana',
    whatClientsSay: 'Qué Dicen Nuestros Clientes',
    readyHire: '¿Listo para contratar o ser contratado?',
    joinUs: 'Únete a miles de empresas y freelancers que ya están creciendo con nosotros.',
    createAccount: 'Crear Cuenta Gratuita',

    loginToAccount: 'Inicia sesión en tu cuenta',
    email: 'Correo electrónico',
    password: 'Contraseña',
    rememberMe: 'Recordarme',
    forgotPassword: '¿Olvidaste tu contraseña?',
    loggingIn: 'Iniciando sesión…',
    login: 'Iniciar sesión',

    createAccount: 'Crear Cuenta',
    fullName: 'Nombre Completo',
    confirmPassword: 'Confirmar Contraseña',
    selectRole: 'Seleccionar Rol:',
    client: 'Cliente',
    freelancer: 'Freelancer',
    creating: 'Creando…',
    createAccountBtn: 'Crear Cuenta',
    alreadyAccount: '¿Ya tienes una cuenta?',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
